# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02c047deda6849fc8504227f4735e76cdbecc03ca7b9281fd0006d44d80cb734eba75d40c8e4f599d67701ff5187515132ccd61d8de2e04f68a0cfe03874532f

test:
  secret_key_base: c711ec89811a1810130b66dffe9ed2dd5f125d59dab1faa1bdedf78f2e9465641955efc9850711d84c56ad4e123636bab2518926485fc1572f36a272b2135065

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
